/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.logic.function;

/**
 *
 * @author Yjares
 */
public class demBeans {
    private int count;
    private String title;
    private String price;
    String productName[] = {"13 Reasons Why", "1984", "A Clash of Kings", " Adventures of Huckleberry Finn", "A Game of Throne", "Artemis Fowl", "Artemis Fowl: The Eternity Code", "Berenstein Bears: Golden Rule", "Blink", "Brave New World", "Divergent", "Eragon", "Everything, Everything", "Fahrenheit 451", "Fifty Shades of Grey", "First 100 Words", "Flowers For Algernon", "Goodnight Moon", "Hamilton: The Revolution", "Harry Potter: Chamber of Secrets", "Inheritance", "Iron Gold", "Justin Bieber: Just Getting Started", "Looking for Alaska", "Lord of the Rings", "Maximum Ride", "Moby Dick", "Necronomicon", "Norse Mythology", "Nothing to Envy", "Oathbringer", "Of Mice and Men", "Ptolemy's Gate", "Ready Player One", "Star Wars: Thrawn", "Steve Jobs", "StrengthsFinder 2.0", "The Amulet of Samarkand", "The Boy on the Wooden Box", "The Catcher in the Rye", "The Da Vinci Code", "The Fault in Our Stars", "The Four Arrangements", "The Girl with a Dragon Tattoo", "The Great Gatsby", "The Hobbit", "The Hunger Games", "The Little Prince", "The Lost Hero", "The Mark of Athena", "The Martian", "The Metamorphosis", "The Missing Ones", "The Old Man and the Sea", "The Perks of Being a Wallflower", "The Women in the Castle", "Twilight", "Ulysses" , "Unbroken", "Wonder"};
    String productPrice[] = {"5.43", "9.99", "19.79", "5.40", "20.49", "7.19", "8.99", "2.43", "2.99", "6.95", "10.58", "8.42", "7.53", "9.70", "9.99", "3.92","7.71", "4.49", "24.99", "6.97", "8.88", "14.99", "13.22", "7.17", "11.90", "9.02", "3.36", "30.99", "11.71", "10.11", "16.99", "5.51", "9.17", "9.99", "14.99", "11.90", "14.08", "9.94", "3.99", "5.49", "6.00", "7.92", "5.83", "9.91", "6.95", "11.06", "6.70", "6.00", "7.49", "8.99", "11.79", "3.99", "11.59", "7.64", "7.11", "16.13", "8.00", "6.49", "9.69", "9.75"};
    String productAuthor[] = {"Jay Asher", "George Orwell", "George R.R. Martin", "Mark Twain", "George R.R. Martin", "Eoin Colfer", "Eoin Colfer", "Mike Berenstain", "K.L Slater", "Aldous Huxley", "Veronica Roth", "Christopher Paolini", "Nicola Yoon", "Ray Bradbury", "E.L. James", "Roger Priddy","Daniel Keyes", "Margaret Wise Brown", "Lin-Manuel Miranda", "J.K Rowling", "Christopher Paoilini", "Pierce Brown", "Justin Bieber", "John Green", "J.R.R Tolkien", "James Patterson", "Herman Melville", "H.P. Lovecraft", "Neil Gaiman", "Barbara Demick", "Brandon Sanderson", "John Steinbeck", "Jonathan Stroud", "Ernest Cline", "Timothy Zahn", "Walter Isaacson", "Tom Rath", "Jonathan Stroud", "Leon Leyson", "J.D Salinger", "Dan Brown", "John Green", "Don Miguel Ruiz", "Stieg Larsson", "F. Scott Fitzgerald", "J.R.R. Tolkien", "Suzanne Collins", "Antoine de Saint-Exupery", "Rick Riordan", "Rick Riordan", "Andy Weir", "Franz Kafka", "Patricia Gibney", "Ernest Hemingway", "Stephen Chbosky", "Jessica Shattuck", "Stephenie Meyer", "James Joyce", "Laura Hillenbrand", "R.J. Palacio"};
    String productDetail[] = {"Paperback - June 14, 2011", "Mass Market Paperback - Unabridged, July 1, 1950", "Hardcover - February 2, 1999", "Paperback - May 19, 1999", "Hardcover - August 1, 1996", "Paperback - June 23, 2009", "Paperback - July 14, 2009", "Paperback - September 28, 2008", "Paperback - May 21, 2013", "Paperback - October 17, 2006", "Hardcover - May 3, 2011", "Paperback - April 26, 2005", "Paperback - March 7, 2017", "Paperback - January 10, 2012", "Paperback - April 3, 2012", "Board Book - May 10, 2011", "Paperback - May 1, 2005", "Board Book - January 23, 2007", "Hardcover - April 12, 2016", "Paperback - August 15, 2000", "Paperback - October 23, 2012", "Hardcover - November 2, 2011", "Hardcover - September 13, 2012", "Paperback - December 28, 2006", "Paperback - October 12, 2005", "Paperback - April 1, 2007", "Paperback - April 24, 1985", "Hardcover - March 27, 2008", "Paperback - February 4, 2012", "Paperback - June 26, 2007", "Paperback - August 30, 2013", "Mass Market Paperback - September 1, 1993", "Paperback - January 1, 2007", "Paperback - June 5, 2012", "Paperback - October 12, 2014", "Paperback - September 15, 2015", "Hardcover - February 1, 2007", "Paperback - May 3, 2004", "Paperback - August 18, 2015", "Paperback - May 1, 1991", "Paperback - March 31, 2009", "Paperback - April 8, 2014", "Paperback - November 7, 1997", "Mass Market Paperback - Unabridged, November 22, 2011", "Paperback - September 30, 2004", "Paperback - September 18, 2012", "Paperback - July 3, 2010", "Paperback - June 29, 2000", "Paperback - Unabridged, April 3, 2012", "Paperback - April 8, 2014", "Paperback - October 28, 2014", "Paperback - September 12, 2009", "Paperback - June 23, 2001", "Paperback - May 5, 1995", "Paperback - August 14, 2012", "Hardcover - Deckle Edge, March 28, 2017", "Paperback - August 15, 2011", "Paperback - June 14, 2009", "Paperback - July 29, 2014", "Hardcover - February 14, 2012"};
    String productDesc[] = {
        "<b>THE #1 NEW YORK TIMES AND INTERNATIONAL BESTSELLER<br><br>**THE BOOK THAT STARTED IT ALL, NOW A NETFLIX ORIGINAL SERIES**<br><br></b>“Eerie, beautiful, and devastating.” —Chicago Tribune<br><br>“A stealthy hit with staying power. . . . thriller-like pacing.” —The New York Times<br><br>“Thirteen Reasons Why will leave you with chills long after you have finished reading.” —Amber Gibson, NPR’s “All Things Considered”<br><br>You can’t stop the future.<br><br> You can’t rewind the past.<br><br>The only way to learn the secret . . . is to press play.<br><br>Clay Jensen returns home from school to find a strange package with his name on it lying on his porch. Inside he discovers several cassette tapes recorded by Hannah Baker—his classmate and crush—who committed suicide two weeks earlier. Hannah's voice tells him that there are thirteen reasons why she decided to end her life. Clay is one of them. If he listens, he'll find out why. Clay spends the night crisscrossing his town with Hannah as his guide. He becomes a firsthand witness to Hannah's pain, and as he follows Hannah’s recorded words throughout his town, what he discovers changes his life forever.", 
        "Written in 1948, 1984 was George Orwell’s chilling prophecy about the future. And while 1984 has come and gone, his dystopian vision of a government that will do anything to control the narrative is timelier than ever...<br><br>“The Party told you to reject the evidence of your eyes and ears. It was their final, most essential command.”<br><br>Winston Smith toes the Party line, rewriting history to satisfy the demands of the Ministry of Truth. With each lie he writes, Winston grows to hate the Party that seeks power for its own sake and persecutes those who dare to commit thoughtcrimes. But as he starts to think for himself, Winston can’t escape the fact that Big Brother is always watching... <br><br>A startling and haunting vision of the world, 1984 is so powerful that it is completely convincing from start to finish. No one can deny the influence of this novel, its hold on the imaginations of multiple generations of readers, or the resiliency of its admonitions—a legacy that seems only to grow with the passage of time.",
        "<b>THE BOOK BEHIND THE THIRD SEASON OF GAME OF THRONES, AN ORIGINAL SERIES NOW ON HBO.</b><br><br>Rarely has there been a tale as gripping, or one as likely to seize the minds and hearts of a generation, as George R. R. Martin's epic high fantasy series. In A Game of Thrones, an ancient kingdom was torn by the ambitions of ruthless men and women; in A Clash of Kings, war, sorcery, and madness swept over the kingdom like a voracious beast of prey. Now, as the brutal struggle for power nears its tumultuous climax, the battered and divided kingdom faces its most terrifying invasion—one that is being spearheaded from beyond the grave. . . .",
        "Referring to Adventures of Huckleberry Finn, H. L. Mencken noted that his discovery of this classic American novel was \"the most stupendous event of my whole life\"; Ernest Hemingway declared that \"all modern American literature stems from this one book,\" while T. S. Eliot called Huck \"one of the permanent symbolic figures of fiction, not unworthy to take a place with Ulysses, Faust, Don Quixote, Don Juan, Hamlet.\"<br><br>The novel's preeminence derives from its wonderfully imaginative re-creation of boyhood adventures along the Mississippi River, its inspired characterization, the author's remarkable ear for dialogue, and the book's understated development of serious underlying themes: \"natural\" man versus \"civilized\" society, the evils of slavery, the innate value and dignity of human beings, and other topics. Most of all, Huckleberry Finn is a wonderful story, filled with high adventure and unforgettable characters.",
        "Long ago, in a time forgotten, a preternatural event threw the seasons out of balance. In a land where summers can last decades and winters a lifetime, trouble is brewing. The cold is returning, and in the frozen wastes to the north of Winterfell, sinister forces are massing beyond the kingdom’s protective Wall. To the south, the king’s powers are failing—his most trusted adviser dead under mysterious circumstances and his enemies emerging from the shadows of the throne. At the center of the conflict lie the Starks of Winterfell, a family as harsh and unyielding as the frozen land they were born to. Now Lord Eddard Stark is reluctantly summoned to serve as the king’s new Hand, an appointment that threatens to sunder not only his family but the kingdom itself.<br><br>Sweeping from a harsh land of cold to a summertime kingdom of epicurean plenty, A Game of Thrones tells a tale of lords and ladies, soldiers and sorcerers, assassins and bastards, who come together in a time of grim omens. Here an enigmatic band of warriors bear swords of no human metal; a tribe of fierce wildlings carry men off into madness; a cruel young dragon prince barters his sister to win back his throne; a child is lost in the twilight between life and death; and a determined woman undertakes a treacherous journey to protect all she holds dear. Amid plots and counter-plots, tragedy and betrayal, victory and terror, allies and enemies, the fate of the Starks hangs perilously in the balance, as each side endeavors to win that deadliest of conflicts: the game of thrones",
        "Twelve-year-old Artemis Fowl is a millionaire, a genius-and, above all, a criminal mastermind. But even Artemis doesn't know what he's taken on when he kidnaps a fairy, Captain Holly Short of the LEPrecon Unit. These aren't the fairies of bedtime stories; these fairies are armed and dangerous. <br><br>Artemis thinks he has them right where he wants them but then they stop playing by the rules.",
        "Artemis Fowl is going straight. As soon as he pulls off the most brilliant criminal feat of his career.<br><br>At least, that's the plan when he attempts to sell his C Cube, a supercomputer built from stolen fairy technology. When his efforts to broker a deal for the Cube with a powerful businessman go terribly wrong, his loyal bodyguard and friend Butler is mortally injured. The only thing that will save him is fairy magic, so once again he must contact his old rival, Holly Short.",
        "Should Sister Bear ignore the new girl at school just because her friends do? The Berenstain Bears and the Golden Rule shows children how choosing to be kind may not always be the easy choice. But it is always the right one.",
        "What if the person you love most in the world was in terrible danger … because of you?<br><br>Three years ago, Toni’s five-year-old daughter Evie disappeared after leaving school. The police have never been able to find her. There were no witnesses, no CCTV, no trace. <br><br>But Toni believes her daughter is alive. And as she begins to silently piece together her memories, the full story of the past begins to reveal itself, and a devastating truth.<br><br>Toni’s mind is trapped in a world of silence, her only chance to save herself is to manage the impossible. She must find a way to make herself heard. She must find her daughter. ",
        "<b>Now more than ever: Aldous Huxley's enduring \"masterpiece ... one of the most prophetic dystopian works of the 20th century\" (Wall Street Journal) must be read and understood by anyone concerned with preserving the human spirit in the face of our \"brave new world\"</b><br><br>Aldous Huxley's profoundly important classic of world literature, Brave New World is a searching vision of an unequal, technologically-advanced future where humans are genetically bred, socially indoctrinated, and pharmaceutically anesthetized to passively uphold an authoritarian ruling order--all at the cost of our freedom, full humanity, and perhaps also our souls.<br><br> “A genius [who] who spent his life decrying the onward march of the Machine” (The New Yorker), Huxley was a man of incomparable talents: equally an artist, a spiritual seeker, and one of history’s keenest observers of human nature and civilization.<br><br> Brave New World, his masterpiece, has enthralled and terrified millions of readers, and retains its urgent relevance to this day as both a warning to be heeded as we head into tomorrow and as thought-provoking, satisfying work of literature. Written in the shadow of the rise of fascism during the 1930s, Brave New World likewise speaks to a 21st-century world dominated by mass-entertainment, technology, medicine and pharmaceuticals, the arts of persuasion, and the hidden influence of elites.",
        "This first book in Veronica Roth's #1 New York Times bestselling Divergent trilogy is the novel the inspired the major motion picture starring Shailene Woodley, Theo James, and Kate Winslet. This dystopian series set in a futuristic Chicago has captured the hearts of millions of teen and adult readers. Perfect for fans of the Hunger Games and Maze Runner series, Divergent and its sequels, Insurgent and Allegiant, are the gripping story of a dystopian world transformed by courage, self-sacrifice, and love. Fans of the Divergent movie will find the book packed with just as much emotional depth and exhilarating action as the film, all told in beautiful, rich language.<br><br> One choice can transform you. Beatrice Prior's society is divided into five factions—Candor (the honest), Abnegation (the selfless), Dauntless (the brave), Amity (the peaceful), and Erudite (the intelligent). Beatrice must choose between staying with her Abnegation family and transferring factions. Her choice will shock her community and herself. But the newly christened Tris also has a secret, one she's determined to keep hidden, because in this world, what makes you different makes you dangerous. Supports the Common Core State Standards.",
        "Perfect for fans of Lord of the Rings, the New York Times bestselling Inheritance Cycle about the dragon rider Eragon has sold over 35 million copies and is an international fantasy sensation.<br><br>Fifteen-year-old Eragon believes that he is merely a poor farm boy—until his destiny as a Dragon Rider is revealed. Gifted with only an ancient sword, a loyal dragon, and sage advice from an old storyteller, Eragon is soon swept into a dangerous tapestry of magic, glory, and power. Now his choices could save—or destroy—the Empire.",
        "<b>The instant #1 New York Times bestseller--soon to be a major motion picture! In theaters May 19, it stars Amandla Stenberg as Maddy and Nick Robinson as Olly.</b><br><br>Risk everything . . . for love.<br><br>What if you couldn’t touch anything in the outside world? Never breathe in the fresh air, feel the sun warm your face . . . or kiss the boy next door? In Everything, Everything, Maddy is a girl who’s literally allergic to the outside world, and Olly is the boy who moves in next door . . . and becomes the greatest risk she’s ever taken.",
        "<b>Ray Bradbury’s internationally acclaimed novel Fahrenheit 451 is a masterwork of twentieth-century literature set in a bleak, dystopian future.</b><br><br>Guy Montag is a fireman. In his world, where television rules and literature is on the brink of extinction, firemen start fires rather than put them out. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden.<br><br>Montag never questions the destruction and ruin his actions produce, returning each day to his bland life and wife, Mildred, who spends all day with her television “family.” But then he meets an eccentric young neighbor, Clarisse, who introduces him to a past where people didn’t live in fear and to a present where one sees the world through the ideas in books instead of the mindless chatter of television.<br><br>When Mildred attempts suicide and Clarisse suddenly disappears, Montag begins to question everything he has ever known. He starts hiding books in his home, and when his pilfering is discovered, the fireman has to run for his life.",
        "<b>MORE THAN 100 MILLION COPIES SOLD WORLDWIDE. NOW A MAJOR MOTION PICTURE</b><br><br>When literature student Anastasia Steele goes to interview young entrepreneur Christian Grey, she encounters a man who is beautiful, brilliant, and intimidating. The unworldly, innocent Ana is startled to realize she wants this man and, despite his enigmatic reserve, finds she is desperate to get close to him. Unable to resist Ana’s quiet beauty, wit, and independent spirit, Grey admits he wants her, too—but on his own terms.<br><br>Shocked yet thrilled by Grey’s singular erotic tastes, Ana hesitates. For all the trappings of success—his multinational businesses, his vast wealth, his loving family—Grey is a man tormented by demons and consumed by the need to control. When the couple embarks on a daring, passionately physical affair, Ana discovers Christian Grey’s secrets and explores her own dark desires.<br><br>This book is intended for mature audiences.",
        "Your little one will soon learn some essential first words and pictures with this bright board book. There are 100 color photographs to look at and talk about, and 100 simple first words to read and learn, too. The pages are made from tough board for hours of fun reading, and the cover is softly padded for little hands to hold.",
        "Oscar-winning film Charly starring Cliff Robertson and Claire Bloom-a mentally challenged man receives an operation that turns him into a genius...and introduces him to heartache.",
        "In a great green room, tucked away in bed, is a little bunny. \"Goodnight room, goodnight moon.\" And to all the familiar things in the softly lit room—to the picture of the three little bears sitting on chairs, to the clocks and his socks, to the mittens and the kittens, to everything one by one—the little bunny says goodnight.<br><br>In this classic of children's literature, beloved by generations of readers and listeners, the quiet poetry of the words and the gentle, lulling illustrations combine to make a perfect book for the end of the day.<br><br>This board book edition is the perfect size for little hands.",
        "<b>Winner of the 2016 Pulitzer Prize for Drama and Eleven Tony Awards, including Best Musical</b><br><br>Lin-Manuel Miranda's groundbreaking musical Hamilton is as revolutionary as its subject, the poor kid from the Caribbean who fought the British, defended the Constitution, and helped to found the United States. Fusing hip-hop, pop, R&B, and the best traditions of theater, this once-in-a-generation show broadens the sound of Broadway, reveals the storytelling power of rap, and claims our country's origins for a diverse new generation.<br><br>HAMILTON: THE REVOLUTION gives readers an unprecedented view of both revolutions, from the only two writers able to provide it. Miranda, along with Jeremy McCarter, a cultural critic and theater artist who was involved in the project from its earliest stages--\"since before this was even a show,\" according to Miranda--traces its development from an improbable perfor­mance at the White House to its landmark opening night on Broadway six years later. In addition, Miranda has written more than 200 funny, revealing footnotes for his award-winning libretto, the full text of which is published here.",
        "The Dursleys were so mean that hideous that summer that all Harry Potter wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he's packing his bags, Harry receives a warning from a strange, impish creature named Dobby who says that if Harry Potter returns to Hogwarts, disaster will strike.<br><br>And strike it does. For in Harry's second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor, Gilderoy Lockheart, a spirit named Moaning Myrtle who haunts the girls' bathroom, and the unwanted attentions of Ron Weasley's younger sister, Ginny.<br><br>But each of these seem minor annoyances when the real trouble begins, and someone--or something--starts turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it possibly be Hagrid, whose mysterious past is finally told? Or could it be the one everyone at Hogwarts most suspects...Harry Potter himself?",
        "<b>Perfect for fans of Lord of the Rings, the New York Times bestselling Inheritance Cycle about the dragon rider Eragon has sold over 35 million copies and is an international fantasy sensation.</b><br><br>Not so very long ago, Eragon—Shadeslayer, Dragon Rider—was nothing more than a poor farm boy, and his dragon, Saphira, only a blue stone in the forest. Now the fate of an entire civilization rests on their shoulders.<br><br>Long months of training and battle have brought victories and hope, but they have also brought heartbreaking loss. And still, the real battle lies ahead: they must confront Galbatorix. When they do, they will have to be strong enough to defeat him. And if they cannot, no one can. There will be no second chances. <br><br>The Rider and his dragon have come further than anyone dared to hope. But can they topple the evil king and restore justice to Alagaësia? And if so, at what cost?<br><br>This is the much-anticipated, astonishing conclusion to the worldwide bestselling Inheritance cycle",
        "Pierce Brown expands the size and scope of his #1 New York Times bestselling Red Rising series with a brand-new adventure of revolution and betrayal among the stars.",
        "<b>\"My story is something I like to share with others, to show people that with enough belief in yourself and what you can accomplish, anything is possible.</b>\"—Justin Bieber<br><br>From Tel Aviv to Tokyo, over the past few years I've traveled around the world and back again. It's been amazing, but it's also hard to believe that not so long ago I was singing on the streets of Stratford, Ontario. I can honestly say that anything is possible, anyone can live the dream, and every day is a blessing.<br><br>Now everywhere I go, I'm met with so much love. It's all about you, my fans, and that's why I'm dedicating my book to everyone who's come to sing along. I want to share the stories of my life on the road with you. From the crazy highs of performing on stage to spending those precious quiet moments with my friends and family, I want to give you a personal backstage pass to my world. It's been exhausting but always eye-opening and amazing.<br><br>It's astonishing to think that so much has happened, and yet this is just the beginning. I'm just getting started.",
        "<b>The award-winning, genre-defining debut from John Green, the #1 international bestselling author of The Fault in Our Stars<br><br>Millions of copies sold!<br><br>- Michael L. Printz Award Winner<br>- Los Angeles Times Book Prize Finalist<br>- NPR's 100 Best-Ever Teen Novels<br>- TIME Magazine's 100 100 Best Young Adult Books of All Time<br>- New York Times bestseller<br>- USA Today bestseller</b><br><br>Before. Miles “Pudge” Halter is done with his safe life at home. His whole life has been one big non-event, and his obsession with famous last words has only made him crave “the Great Perhaps” even more (Francois Rabelais, poet). He heads off to the sometimes crazy and anything-but-boring world of Culver Creek Boarding School, and his life becomes the opposite of safe. Because down the hall is Alaska Young. The gorgeous, clever, funny, sexy, self-destructive, screwed up, and utterly fascinating Alaska Young. She is an event unto herself. She pulls Pudge into her world, launches him into the Great Perhaps, and steals his heart. Then. . . .<br><br>After. Nothing is ever the same.",
        "<b>One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them</b><br><br>In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell by chance into the hands of the hobbit Bilbo Baggins.<br><br>From Sauron's fastness in the Dark Tower of Mordor, his power spread far and wide. Sauron gathered all the Great Rings to him, but always he searched for the One Ring that would complete his dominion.<br><br>When Bilbo reached his eleventy-first birthday he disappeared, bequeathing to his young cousin Frodo the Ruling Ring and a perilous quest: to journey across Middle-earth, deep into the shadow of the Dark Lord, and destroy the Ring by casting it into the Cracks of Doom.<br><br>The Lord of the Rings tells of the great quest undertaken by Frodo and the Fellowship of the Ring: Gandalf the Wizard; the hobbits Merry, Pippin, and Sam; Gimli the Dwarf; Legolas the Elf; Boromir of Gondor; and a tall, mysterious stranger called Strider.<br><br>This new edition includes the fiftieth-anniversary fully corrected text setting and, for the first panttime, an extensive new index.",
        "In James Patterson's blockbuster series, fourteen-year-old Maximum Ride, better known as Max, knows what it's like to soar above the world. She and all the members of the \"flock\"--Fang, Iggy, Nudge, Gasman and Angel--are just like ordinary kids--only they have wings and can fly.<br><br>It may seem like a dream come true to some, but their lives can morph into a living nightmare at any time...like when Angel, the youngest member of the flock, is kidnapped and taken back to the \"School\" where she and the others were experimented on by a crew of wack jobs. Her friends brave a journey to blazing hot Death Valley, CA, to save Angel, but soon enough, they find themselves in yet another nightmare--this one involving fighting off the half-human, half-wolf \"Erasers\" in New York City. Whether in the treetops of Central Park or in the bowels of the Manhattan subway system, Max and her adopted family take the ride of their lives.<br><br> Along the way Max discovers from her old friend and father-figure Jeb--now her betrayed and greatest enemy--that her purpose is save the world--but can she?",
        "With an Introduction and Notes by David Herd. Lecturer in English and American Literature at the University of Kent at Canterbury Moby-Dick is the story of Captain Ahab's quest to avenge the whale that 'reaped' his leg. The quest is an obsession and the novel is a diabolical study of how a man becomes a fanatic. But it is also a hymn to democracy. Bent as the crew is on Ahab s appalling crusade, it is equally the image of a co-operative community at work: all hands dependent on all hands, each individual responsible for the security of each. Among the crew is Ishmael, the novel's narrator, ordinary sailor, and extraordinary reader. Digressive, allusive, vulgar, transcendent, the story Ishmael tells is above all an education: in the practice of whaling, in the art of writing.",
        "<b>WIKIPEDIA says: 'H.P. Lovecraft's reputation has grown tremendously over the decades, and he is now commonly regarded as one of the most important horror writers of the 20th century, exerting an influence that is widespread, though often indirect.'</b><br><br>H.P. Lovecraft's tales of the tentacled Elder God Cthulhu and his pantheon of alien deities were initially written for the pulp magazines of the 1920s and '30s. These astonishing tales blend elements of horror, science fiction and cosmic terror that are as powerful today as they were when they were first published.",
        "Introducing an instant classic—master storyteller Neil Gaiman presents a dazzling version of the great Norse myths.<br><br>Neil Gaiman has long been inspired by ancient mythology in creating the fantastical realms of his fiction. Now he turns his attention back to the source, presenting a bravura rendition of the great northern tales.",
        "A National Book Award finalist and National Book Critics Circle finalist, Barbara Demick’s Nothing to Envy is a remarkable view into North Korea, as seen through the lives of six ordinary citizens.<br><br>Award-winning journalist Barbara Demick follows the lives of six North Korean citizens over fifteen years—a chaotic period that saw the death of Kim Il-sung, the rise to power of his son Kim Jong-il, and a devastating famine that killed one-fifth of the population. Demick brings to life what it means to be living under the most repressive totalitarian regime today—an Orwellian world that is by choice not connected to the Internet, where displays of affection are punished, informants are rewarded, and an offhand remark can send a person to the gulag for life. Demick takes us deep inside the country, beyond the reach of government censors, and through meticulous and sensitive reporting we see her subjects fall in love, raise families, nurture ambitions, and struggle for survival. One by one, we witness their profound, life-altering disillusionment with the government and their realization that, rather than providing them with lives of abundance, their country has betrayed them.",
        "<b>The eagerly awaited sequel to the #1 New York Times bestselling Words of Radiance, from epic fantasy author Brandon Sanderson at the top of his game.</b><br><br>In Oathbringer, the third volume of the New York Times bestselling Stormlight Archive, humanity faces a new Desolation with the return of the Voidbringers, a foe with numbers as great as their thirst for vengeance.<br><br>Dalinar Kholin’s Alethi armies won a fleeting victory at a terrible cost: The enemy Parshendi summoned the violent Everstorm, which now sweeps the world with destruction, and in its passing awakens the once peaceful and subservient parshmen to the horror of their millennia-long enslavement by humans. While on a desperate flight to warn his family of the threat, Kaladin Stormblessed must come to grips with the fact that the newly kindled anger of the parshmen may be wholly justified.",
        "A controversial tale of friendship and tragedy during the Great Depression<br><br>They are an unlikely pair: George is \"small and quick and dark of face\"; Lennie, a man of tremendous size, has the mind of a young child. Yet they have formed a \"family,\" clinging together in the face of loneliness and alienation.<br><br>Laborers in California's dusty vegetable fields, they hustle work when they can, living a hand-to-mouth existence. For George and Lennie have a plan: to own an acre of land and a shack they can call their own. When they land jobs on a ranch in the Salinas Valley, the fulfillment of their dream seems to be within their grasp. But even George cannot guard Lennie from the provocations of a flirtatious woman, nor predict the consequences of Lennie's unswerving obedience to the things George taught him.",
        "'Ptolemy's Gate' is the climax of the 'Bartimaeus Trilogy' in which a long-standing conspiracy comes to fruition and Bartimaeus, Nathaniel and Kitty face a final enemy which threatens them all.",
        "In the year 2044, reality is an ugly place. The only time teenage Wade Watts really feels alive is when he's jacked into the virtual utopia known as the OASIS. Wade's devoted his life to studying the puzzles hidden within this world's digital confines—puzzles that are based on their creator's obsession with the pop culture of decades past and that promise massive power and fortune to whoever can unlock them. But when Wade stumbles upon the first clue, he finds himself beset by players willing to kill to take this ultimate prize. The race is on, and if Wade's going to survive, he'll have to win—and confront the real world he's always been so desperate to escape.",
        "In this definitive novel, readers will follow Thrawn’s rise to power—uncovering the events that created one of the most iconic villains in Star Wars history.<br><br>One of the most cunning and ruthless warriors in the history of the Galactic Empire, Grand Admiral Thrawn is also one of the most captivating characters in the Star Wars universe, from his introduction in bestselling author Timothy Zahn’s classic Heir to the Empire through his continuing adventures in Dark Force Rising, The Last Command, and beyond. But Thrawn’s origins and the story of his rise in the Imperial ranks have remained mysterious. Now, in Star Wars: Thrawn, Timothy Zahn chronicles the fateful events that launched the blue-skinned, red-eyed master of military strategy and lethal warfare into the highest realms of power—and infamy.",
        "Walter Isaacson’s “enthralling” (The New Yorker) worldwide bestselling biography of Apple co-founder Steve Jobs—the inspiration for the movie Steve Jobs starring Michael Fassbender, Kate Winslet, Seth Rogen, and Jeff Daniels, directed by Danny Boyle with a screenplay by Aaron Sorkin.<br><br>Based on more than forty interviews with Steve Jobs conducted over two years—as well as interviews with more than 100 family members, friends, adversaries, competitors, and colleagues—Walter Isaacson has written a riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur whose passion for perfection and ferocious drive revolutionized six industries: personal computers, animated movies, music, phones, tablet computing, and digital publishing. Isaacson’s portrait touched millions of readers.",
        "Do you have the opportunity to do what you do best every day? <br><br>Chances are, you don't. All too often, our natural talents go untapped. From the cradle to the cubicle, we devote more time to fixing our shortcomings than to developing our strengths. <br><br>To help people uncover their talents, Gallup introduced the first version of its online assessment, StrengthsFinder, in 2001 which ignited a global conversation and helped millions to discover their top five talents.",
        "Nathaniel is a magician's apprentice, taking his first lessons in the arts of magic. But when a devious hot-shot wizard named Simon Lovelace ruthlessly humiliates Nathaniel in front of his elders, Nathaniel decides to kick up his education a few notches and show Lovelace who's boss. With revenge on his mind, he summons the powerful djinni, Bartimaeus. But summoning Bartimaeus and controlling him are two different things entirely, and when Nathaniel sends the djinni out to steal Lovelace's greatest treasure, the Amulet of Samarkand, he finds himself caught up in a whirlwind of magical espionage, murder, and rebellion",
        "<b>“Much like The Boy In the Striped Pajamas or The Book Thief,” this remarkable memoir from Leon Leyson, one of the youngest children to survive the Holocaust on Oskar Schindler’s list, “brings to readers a story of bravery and the fight for a chance to live” (VOYA).</b><br><br>This, the only memoir published by a former Schindler’s list child, perfectly captures the innocence of a small boy who goes through the unthinkable. Leon Leyson (born Leib Lezjon) was only ten years old when the Nazis invaded Poland and his family was forced to relocate to the Krakow ghetto. With incredible luck, perseverance, and grit, Leyson was able to survive the sadism of the Nazis, including that of the demonic Amon Goeth, commandant of Plaszow, the concentration camp outside Krakow.<br><br>Ultimately, it was the generosity and cunning of one man, Oskar Schindler, who saved Leon Leyson’s life, and the lives of his mother, his father, and two of his four siblings, by adding their names to his list of workers in his factory—a list that became world renowned: Schindler’s list",
        "Anyone who has read J.D. Salinger's New Yorker stories ? particularly A Perfect Day for Bananafish, Uncle Wiggily in Connecticut, The Laughing Man, and For Esme ? With Love and Squalor, will not be surprised by the fact that his first novel is fully of children. The hero-narrator of THE CATCHER IN THE RYE is an ancient child of sixteen, a native New Yorker named Holden Caulfield.<br><br> Through circumstances that tend to preclude adult, secondhand description, he leaves his prep school in Pennsylvania and goes underground in New York City for three days. The boy himself is at once too simple and too complex for us to make any final comment about him or his story. Perhaps the safest thing we can say about Holden is that he was born in the world not just strongly attracted to beauty but, almost, hopelessly impaled on it. There are many voices in this novel: children's voices, adult voices, underground voices-but Holden's voice is the most eloquent of all. Transcending his own vernacular, yet remaining marvelously faithful to it, he issues a perfectly articulated cry of mixed pain and pleasure. However, like most lovers and clowns and poets of the higher orders, he keeps most of the pain to, and for, himself. The pleasure he gives away, or sets aside, with all his heart. It is there for the reader who can handle it to keep.",
        "<b>PREMIUM MASS MARKET EDITION<br>#1 Worldwide Bestseller—More Than 80 Million Copies Sold</b><br><br>As millions of readers around the globe have already discovered, The Da Vinci Code is a reading experience unlike any other. Simultaneously lightning-paced, intelligent, and intricately layered with remarkable research and detail, Dan Brown's novel is a thrilling masterpiece—from its opening pages to its stunning conclusion.",
        "Despite the tumor-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal, her final chapter inscribed upon diagnosis. But when a gorgeous plot twist named Augustus Waters suddenly appears at Cancer Kid Support Group, Hazel’s story is about to be completely rewritten.<br><br>Insightful, bold, irreverent, and raw, The Fault in Our Stars is award-winning-author John Green’s most ambitious and heartbreaking work yet, brilliantly exploring the funny, thrilling, and tragic business of being alive and in love. ",
        "In The Four Agreements, bestselling author don Miguel Ruiz reveals the source of self-limiting beliefs that rob us of joy and create needless suffering. Based on ancient Toltec wisdom, The Four Agreements offer a powerful code of conduct that can rapidly transform our lives to a new experience of freedom, true happiness, and love.<br><br>• A New York Times bestseller for over 8 years<br>• Over 6 million copies sold in the U.S.<br>• Translated into 40 languages worldwide",
        "<b>The Girl in the Spider’s Web, the new book in the Millennium Series, is available now!</b><br><br>Murder mystery, family saga, love story, and financial intrigue combine into one satisfyingly complex and entertainingly atmospheric novel.<br><br>Harriet Vanger, a scion of one of Sweden's wealthiest families disappeared over forty years ago. All these years later, her aged uncle continues to seek the truth. He hires Mikael Blomkvist, a crusading journalist recently trapped by a libel conviction, to investigate. He is aided by the pierced and tattooed punk prodigy Lisbeth Salander. Together they tap into a vein of unfathomable iniquity and astonishing corruption.",
        "The authentic edition from Fitzgerald's original publisher. This edition approved by the Holden-Crowther Literary Organisation.<br><br>The Great Gatsby, F. Scott Fitzgerald's third book, stands as the supreme achievement of his career. This exemplary novel of the Jazz Age has been acclaimed by generations of readers. The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted \"gin was the national drink and sex the national obsession,\" it is an exquisitely crafted tale of America in the 1920s.<br><br>The Great Gatsby is one of the great classics of twentieth-century literature.",
        "<b>Now a major motion picture<br>A great modern classic and the prelude to THE LORD OF THE RINGS<br><br></b>Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day to whisk him away on an adventure. They have launched a plot to raid the treasure hoard guarded by Smaug the Magnificent, a large and very dangerous dragon. Bilbo reluctantly joins their quest, unaware that on his journey to the Lonely Mountain he will encounter both a magic ring and a frightening creature known as Gollum. <br><br>“A glorious account of a magnificent adventure, filled with suspense and seasoned with a quiet humor that is irresistible . . . All those, young or old, who love a fine adventurous tale, beautifully told, will take The Hobbit to their hearts.” – New York Times Book Review",
        "In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. Long ago the districts waged war on the Capitol and were defeated. As part of the surrender terms, each district agreed to send one boy and one girl to appear in an annual televised event called, \"The Hunger Games,\" a fight to the death on live TV. Sixteen-year-old Katniss Everdeen, who lives alone with her mother and younger sister, regards it as a death sentence when she is forced to represent her district in the Games. The terrain, rules, and level of audience participation may change but one thing is constant: kill or be killed.",
        "Few stories are as widely read and as universally cherished by children and adults alike as The Little Prince. Richard Howard's translation of the beloved classic beautifully reflects Saint-Exupéry's unique and gifted style. Howard, an acclaimed poet and one of the preeminent translators of our time, has excelled in bringing the English text as close as possible to the French, in language, style, and most important, spirit. The artwork in this edition has been restored to match in detail and in color Saint-Exupéry's original artwork. Combining Richard Howard's translation with restored original art, this definitive English-language edition of The Little Prince will capture the hearts of readers of all ages.",
        "Jason has a problem. He doesn't remember anything before waking up on a school bus holding hands with a girl. Apparently she's his girlfriend Piper, his best friend is a kid named Leo, and they're all students in the Wilderness School, a boarding school for \"bad kids.\" What he did to end up here, Jason has no idea-except that everything seems very wrong.<br><br>Piper has a secret. Her father has been missing for three days, and her vivid nightmares reveal that he's in terrible danger. Now her boyfriend doesn't recognize her, and when a freak storm and strange creatures attack during a school field trip, she, Jason, and Leo are whisked away to someplace called Camp Half-Blood. What is going on? <br><br>Leo has a way with tools. His new cabin at Camp Half-Blood is filled with them. Seriously, the place beats Wilderness School hands down, with its weapons training, monsters, and fine-looking girls. What's troubling is the curse everyone keeps talking about, and that a camper's gone missing. Weirdest of all, his bunkmates insist they are all-including Leo-related to a god",
        "In The Son of Neptune, Percy, Hazel, and Frank met in Camp Jupiter, the Roman equivalent of Camp Halfblood, and traveled to the land beyond the gods to complete a dangerous quest. The third book in the Heroes of Olympus series will unite them with Jason, Piper, and Leo. But they number only six--who will complete the Prophecy of Seven?<br><br>The Greek and Roman demigods will have to cooperate in order to defeat the giants released by the Earth Mother, Gaea. Then they will have to sail together to the ancient land to find the Doors of Death. What exactly are the Doors of Death? Much of the prophecy remains a mystery. . . .<br><br>With old friends and new friends joining forces, a marvelous ship, fearsome foes, and an exotic setting, The Mark of Athena is be another unforgettable adventure by master storyteller Rick Riordan",
        "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars.<br><br>Now, he's sure he'll be the first person to die there.<br><br>After a dust storm nearly kills him and forces his crew to evacuate while thinking him dead, Mark finds himself stranded and completely alone with no way to even signal Earth that he’s alive—and even if he could get word out, his supplies would be gone long before a rescue could arrive. <br><br>Chances are, though, he won't have time to starve to death. The damaged machinery, unforgiving environment, or plain-old \"human error\" are much more likely to kill him first. <br><br>But Mark isn't ready to give up yet. Drawing on his ingenuity, his engineering skills—and a relentless, dogged refusal to quit—he steadfastly confronts one seemingly insurmountable obstacle after the next. Will his resourcefulness be enough to overcome the impossible odds against him?",
        "\"The Metamorphosis\" (original German title: \"Die Verwandlung\") is a short novel by Franz Kafka, first published in 1915. It is often cited as one of the seminal works of fiction of the 20th century and is widely studied in colleges and universities across the western world. The story begins with a traveling salesman, Gregor Samsa, waking to find himself transformed into an insect.",
        "The hole they dug was not deep. A white flour bag encased the little body. Three small faces watched from the window, eyes black with terror. <br><br>The child in the middle spoke without turning his head. ‘I wonder which one of us will be next?’<br><br>When a woman’s body is discovered in a cathedral and hours later a young man is found hanging from a tree outside his home, Detective Lottie Parker is called in to lead the investigation. Both bodies have the same distinctive tattoo clumsily inscribed on their legs. It’s clear the pair are connected, but how? ",
        "The Old Man and the Sea is one of Hemingway's most enduring works. Told in language of great simplicity and power, it is the story of an old Cuban fisherman, down on his luck, and his supreme ordeal -- a relentless, agonizing battle with a giant marlin far out in the Gulf Stream. <br><br>Here Hemingway recasts, in strikingly contemporary style, the classic theme of courage in the face of defeat, of personal triumph won from loss. Written in 1952, this hugely successful novella confirmed his power and presence in the literary world and played a large part in his winning the 1954 Nobel Prize for Literature.",
        "Read the cult-favorite coming of age story that takes a sometimes heartbreaking, often hysterical, and always honest look at high school in all its glory. Also a major motion picture starring Logan Lerman and Emma Watson, The Perks of Being a Wallflower is a funny, touching, and haunting modern classic.<br><br>The critically acclaimed debut novel from Stephen Chbosky, Perks follows observant “wallflower” Charlie as he charts a course through the strange world between adolescence and adulthood. First dates, family drama, and new friends. Sex, drugs, and The Rocky Horror Picture Show. Devastating loss, young love, and life on the fringes. Caught between trying to live his life and trying to run from it, Charlie must learn to navigate those wild and poignant roller-coaster days known as growing up.<br><br>A #1 New York Times best seller for more than a year, an American Library Association Best Book for Young Adults (2000) and Best Book for Reluctant Readers (2000), and with millions of copies in print, this novel for teen readers (or “wallflowers” of more-advanced age) will make you laugh, cry, and perhaps feel nostalgic for those moments when you, too, tiptoed onto the dance floor of life.",
        "Three women, haunted by the past and the secrets they hold<br><br>Set at the end of World War II, in a crumbling Bavarian castle that once played host to all of German high society, a powerful and propulsive story of three widows whose lives and fates become intertwined—an affecting, shocking, and ultimately redemptive novel from the author of the New York Times Notable Book The Hazards of Good Breeding.",
        "Isabella Swan's move to Forks, a small, perpetually rainy town in Washington, could have been the most boring move she ever made. But once she meets the mysterious and alluring Edward Cullen, Isabella's life takes a thrilling and terrifying turn. Up until now, Edward has managed to keep his vampire identity a secret in the small community he lives in, but now nobody is safe, especially Isabella, the person Edward holds most dear. The lovers find themselves balanced precariously on the point of a knife-between desire and danger.Deeply romantic and extraordinarily suspenseful, Twilight captures the struggle between defying our instincts and satisfying our desires. This is a love story with bite.",
        "COMPLETE AND UNABRIDGED. With a new Introduction by Cedric Watts, Research Professor of English, University of Sussex. James Joyces astonishing masterpiece, Ulysses, tells of the diverse events which befall Leopold Bloom and Stephen Dedalus in Dublin on 16 June 1904, during which Blooms voluptuous wife, Molly, commits adultery. Initially deemed obscene in England and the USA, this richly-allusive novel, revolutionary in its Modernistic experimentalism, was hailed as a work of genius by W. B. Yeats, T. S. Eliot and Ernest Hemingway. Scandalously frank, wittily erudite, mercurially eloquent, resourcefully comic and generously humane, Ulysses offers the reader a life-changing experience.",
        "In boyhood, Louis Zamperini was an incorrigible delinquent. As a teenager, he channeled his defiance into running, discovering a prodigious talent that had carried him to the Berlin Olympics. But when World War II began, the athlete became an airman, embarking on a journey that led to a doomed flight on a May afternoon in 1943. When his Army Air Forces bomber crashed into the Pacific Ocean, against all odds, Zamperini survived, adrift on a foundering life raft. Ahead of Zamperini lay thousands of miles of open ocean, leaping sharks, thirst and starvation, enemy aircraft, and, beyond, a trial even greater. Driven to the limits of endurance, Zamperini would answer desperation with ingenuity; suffering with hope, resolve, and humor; brutality with rebellion. His fate, whether triumph or tragedy, would be suspended on the fraying wire of his will.",
        "I won't describe what I look like. Whatever you're thinking, it's probably worse. <br><br>August Pullman was born with a facial difference that, up until now, has prevented him from going to a mainstream school. Starting 5th grade at Beecher Prep, he wants nothing more than to be treated as an ordinary kid—but his new classmates can’t get past Auggie’s extraordinary face. WONDER, now a #1 New York Times bestseller and included on the Texas Bluebonnet Award master list, begins from Auggie’s point of view, but soon switches to include his classmates, his sister, her boyfriend, and others. These perspectives converge in a portrait of one community’s struggle with empathy, compassion, and acceptance. "
    };
    

    public String getTitle() {
        return title;
    }

    public void setTitle(int i) {
        this.title = productName[i];
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(int i) {
        this.price = productPrice[i];
    }

    public String getDetail(int i) {
        return productDetail[i];
    }

    public String getDesc(int i) {
        return productDesc[i];
    }

    public int getCount() {
        return count;
    }

    public void setCount(int i) {
        this.count = i;
    }

    public String getTitle2(int i) {
        return productName[i];
    }

    public String getPrice2(int i) {
        return productPrice[i];
    }
    
    public String getAuthor(int i) {
        return productAuthor[i];
    }
}
